compressionLevel: mixed

enableGlobalCache: true

nmMode: hardlinks-global

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

# TODO: Upgrade to Yarn 4 - nmMode: hardlinks-global requires Yarn 4+
yarnPath: .yarn/releases/yarn-3.2.0.cjs
