export const RESOLUTION = {
  MINUTE: 'MINUTE',
  HOUR: 'HOUR',
  DAY: 'DAY',
  DAY_ADJUSTED: 'DAY_ADJUSTED'
}

export const HOLDING_TYPE = {
  EQUITY: 'EQUITY',
  OPTION: 'OPTION'
}

export const TRANSACTION_TYPE = {
  BUY_EQUITY: 'BUY_EQUITY'
}
